### ISSUE TITLE
Can specific rsa-key be chosen?

### ISSUE THREAD

**Issue by coffius** [shmishleniy/sbt-deploy-ssh#1]
I have faced with a situation where I need to set specific rsa-key for deployment. In my case it is circleci.com. Circleci creates a key file with name like this `id_77ee67284d065defda812bd3aaaaaa9d` when you add ssh-key in it. Now you need to copy this file to `id_rsa` each time before deployment. It would be great if `sbt-deploy-ssh` has possibility to set a specific key file instead of default id_rsa

**Comment by shmishleniy** [comment]
You can try create directory somewhere and put to it your key with name id_rsa.
Then you need to set `sshDir` in ServerConfig (or in config file)

ServerConfig(name: String,
                          host: String,
                          user: Option[String] = None,
                          password: Option[String] = None,
                          passphrase: Option[String] = None,
                          port: Option[Int] = None,
                          sshDir: Option[String] = None)

**Comment by shmishleniy** [comment]
@coffius Please see above

**Comment by shmishleniy** [comment]
Added `sshKeyFile` field to config.
Now you can specify key you want to use.
Please see readme.
