### ISSUE TITLE
Two Seprate Configs

### ISSUE THREAD

**Issue by nima-roohi** [shmishleniy/sbt-deploy-ssh#15]
Thank you for your great plugin.
Is the following scenario supported?

I have two jar files and want to deploy both. However, one contains all dependencies and hence is a big file, and the other is everything I wrote and hence is very small. The big one rarely changes, but the small one changes frequently.

So, ideally, I prefer to be able to tell `deploy-ssh` what should be deployed: the `big.jar` or `small.jar`. Is that possible?

Thank you

**Comment by shmishleniy** [comment]
Hi,

single project definition produces more than one jar ?
if few project you can setup `deployArtifacts` separate, in case of single project definition you can try to use scopes:
https://www.scala-sbt.org/1.x/docs/Scope-Delegation.html

here is example:
```
lazy val Small = config("small")
lazy val Large = config("large")

lazy val example = project.in(file(".")).configs(Large).settings(
  mainClass in (Compile, run) := Some("example.App"),
  inConfig(Large)(
    defaultDeployConfig ++ 
    Seq(
      deployArtifacts ++= Seq(
        ArtifactSSH("path/to/large.jar", "tmp/example")
      ),
      deploySshExecBefore ++= Seq(
        (ssh: SSH) => ssh.shell{ shell =>
          shell.execute("touch hello_large")
        }
      ),
    )
  ),
  inConfig(Small)(
    defaultDeployConfig ++ 
    Seq(
      deployArtifacts ++= Seq(
        ArtifactSSH("path/to/small.jar", "tmp/example")
      ),
    )
  ),
)

val defaultDeployConfig = deployssh.DeploySSH.projectSettings ++ Seq(
  deployConfigs ++= Seq(
    ServerConfig(name="server1", host="167.99.138.184", user=Some("root")),
  ),
  deploySshExecBefore ++= Seq(
    (ssh: SSH) => ssh.shell{ shell =>
      shell.execute("touch hello")
    }
  ),
  deploySshExecAfter ++= Seq(
    (ssh: SSH) => ssh.shell{ shell =>
      shell.execute("touch hello_done")
    }
  ),
)
```

**Comment by shmishleniy** [comment]
Hi,

single project definition produces more than one jar ?
if few project you can setup deployArtifacts separate, in case of single project definition you can try to use scopes:
https://www.scala-sbt.org/1.x/docs/Scope-Delegation.html

here is example:

lazy val Small = config("small")
lazy val Large = config("large")

lazy val example = project.in(file(".")).configs(Large).settings(
  mainClass in (Compile, run) := Some("example.App"),
  inConfig(Large)(
    defaultDeployConfig ++ 
    Seq(
      deployArtifacts ++= Seq(
        ArtifactSSH("path/to/large.jar", "tmp/example")
      ),
      deploySshExecBefore ++= Seq(
        (ssh: SSH) => ssh.shell{ shell =>
          shell.execute("touch hello_large")
        }
      ),
    )
  ),
  inConfig(Small)(
    defaultDeployConfig ++ 
    Seq(
      deployArtifacts ++= Seq(
        ArtifactSSH("path/to/small.jar", "tmp/example")
      ),
    )
  ),
)

val defaultDeployConfig = deployssh.DeploySSH.projectSettings ++ Seq(
  deployConfigs ++= Seq(
    ServerConfig(name="server1", host="server1.com", user=Some("root")),
  ),
  deploySshExecBefore ++= Seq(
    (ssh: SSH) => ssh.shell{ shell =>
      shell.execute("touch hello")
    }
  ),
  deploySshExecAfter ++= Seq(
    (ssh: SSH) => ssh.shell{ shell =>
      shell.execute("touch hello_done")
    }
  ),
)

**Comment by shmishleniy** [comment]
Hi,

single project definition produces more than one jar ?
if few project you can setup deployArtifacts separate, in case of single project definition you can try to use scopes:
https://www.scala-sbt.org/1.x/docs/Scope-Delegation.html

here is example:
```
lazy val Small = config("small")
lazy val Large = config("large")

lazy val example = project.in(file(".")).configs(Large).settings(
  mainClass in (Compile, run) := Some("example.App"),
  inConfig(Large)(
    defaultDeployConfig ++ 
    Seq(
      deployArtifacts ++= Seq(
        ArtifactSSH("path/to/large.jar", "tmp/example")
      ),
      deploySshExecBefore ++= Seq(
        (ssh: SSH) => ssh.shell{ shell =>
          shell.execute("touch hello_large")
        }
      ),
    )
  ),
  inConfig(Small)(
    defaultDeployConfig ++ 
    Seq(
      deployArtifacts ++= Seq(
        ArtifactSSH("path/to/small.jar", "tmp/example")
      ),
    )
  ),
)

val defaultDeployConfig = deployssh.DeploySSH.projectSettings ++ Seq(
  deployConfigs ++= Seq(
    ServerConfig(name="server1", host="server1.com", user=Some("root")),
  ),
  deploySshExecBefore ++= Seq(
    (ssh: SSH) => ssh.shell{ shell =>
      shell.execute("touch hello")
    }
  ),
  deploySshExecAfter ++= Seq(
    (ssh: SSH) => ssh.shell{ shell =>
      shell.execute("touch hello_done")
    }
  ),
)
```

**Comment by shmishleniy** [comment]
usage:
`large:deploySsh server1`
or
`small:deploySsh server1`
