### ISSUE TITLE
Feature Request: Passphrase prompt

### ISSUE THREAD

**Issue by wobu** [shmishleniy/sbt-deploy-ssh#2]
Hey there,

following feature would be nice:

Instead of declaring a passphrase for SSH keys as plain text in the configuration, it could be requested by a prompt each time when needed.

Currently the library https://github.com/dacr/jassh doesn't provide an implementation for this.

A simple implementation could be done with this:

```
private class MyUserInfo(val state: State) extends UserInfo {
  var password: String = ""
  var passphrase: String = ""
  val console = System.console()

  override def getPassphrase: String = passphrase

  override def getPassword: String = password

  override def promptPassword(str: String) = {
    println(str)
    println("Please enter Password:")
    console.readPassword().foreach(password += _)
    true
  }

  override def promptPassphrase(str: String) = {
    println(str)
    println("Please enter Passphrase:")
    console.readPassword().foreach(passphrase += _)
    true
  }

  override def promptYesNo(str: String): Boolean = {
    print(str)
    print("(y/n)")
    println()
    readLine().equalsIgnoreCase("y")
  }

  override def showMessage(str: String) = {
    println(str)
  }
}
```

**Comment by shmishleniy** [comment]
Hi, thanks for your comment. If you want  you can create merge request, or I will implement it in future.

**Comment by tellnobody1** [comment]
This will create problems with automated tools. As option it won't be implemented. If you still need this feature then create new merge request.
