### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ruioliveiras** [shmishleniy/sbt-deploy-ssh#3]
Your REAME have incorrect things:

Is not 'deployResourceConfigFile' but 'deployResourceConfigFiles'

**Comment by shmishleniy** [comment]
Thanks! [Fixed](https://github.com/shmishleniy/sbt-deploy-ssh/commit/38af159a10f9579e88fc6d5e8df99c1aeec1fcf0)

**Comment by ruioliveiras** [comment]
:+1: 

Also without _'import deployssh.DeploySSH._'_ we get  _'error: not found: value ArtifactSSH'_

**Comment by shmishleniy** [comment]
Fixed in 1.3
