### ISSUE TITLE
deployConfigsLoaded doesn't resolve config references

### ISSUE THREAD

**Issue by qwe2** [shmishleniy/sbt-deploy-ssh#9]
Say I have a deploy config like this:

```conf
servers = [
  {
    name = "server_0"
    host = ${app.host}
  }
]

app.host = test-host
```

then calling `deploySsh server_0` will result in `com.typesafe.config.ConfigException$NotResolved` exception because the config is only parsed but not resolved. This feature would be useful for example in CI jobs where I want to put parts of the deploy config into environment variables.

Currently this could be worked around by defining `deployConfigsLoaded` instead of `deployResourceConfigFiles` (or any other alternatives of that). The fix is pretty easy: call `.resolve()` in the `deployConfigsLoaded` `TaskKey` definition.

I'm using it like this currently:

```scala
deployConfigsLoaded := Seq(ConfigFactory.parseFile(file("ssh-deploy.conf")).resolve())
```

**Comment by shmishleniy** [comment]
Thanks for improvement!
